import { useEffect, useRef, useState } from "react";
import { Modal } from "@/components/Common";
import { paymentStatus, payTransaction, verifyPayment } from "@/services/apiServices";
import type { Transaction } from "@/types";

export function PaymentModal({ transaction, phone, onClose, onSuccess }: { transaction: Transaction; phone: string; onClose:()=>void; onSuccess:()=>void }) {
  const [state,setState]=useState<"form"|"waiting"|"recovery"|"success"|"failed">("form"); const [phoneInput,setPhoneInput]=useState(phone); const [paymentId,setPaymentId]=useState<string|null>(null); const [code,setCode]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const attempts=useRef(0);
  useEffect(()=>()=>{ attempts.current=999; },[]);
  async function poll(id:string){ attempts.current+=1; try { const p=await paymentStatus(id); if(p.status==="successful"){setState("success"); onSuccess(); return;} if(["failed","cancelled","expired"].includes(p.status)){setState("failed");setError(p.status==="expired"?"The payment request expired.":"The payment was not completed.");return;} if(attempts.current>=20){setState("recovery");return;} setTimeout(()=>void poll(id),3000); } catch { setState("recovery"); } }
  async function pay(){ if(!/^\+?254|^0?7/.test(phoneInput.replace(/\s/g,""))){setError("Enter a valid Kenyan phone number.");return;} setBusy(true);setError("");try{const result=await payTransaction(transaction.id,phoneInput);setPaymentId(result.payment_id);setState("waiting");attempts.current=0;void poll(result.payment_id);}catch(e){setState("failed");setError(e instanceof Error?e.message:"Unable to start payment.");}finally{setBusy(false);} }
  async function verify(){if(!paymentId)return;setBusy(true);setError("");try{const result=await verifyPayment(paymentId,code.trim().toUpperCase());if(!result.verified){setError(result.message||"Payment could not be verified.");return;}setState("success");onSuccess();}catch(e){setError(e instanceof Error?e.message:"Could not verify payment.");}finally{setBusy(false);}}
  return <Modal title="Unlock contact" onClose={state==="waiting"?()=>{}:onClose}>{state==="form"&&<><p className="muted">Pay <strong>KSh {transaction.fee_amount}</strong> to complete this connection and unlock the contact.</p><label className="field"><span>M-Pesa phone number</span><input value={phoneInput} onChange={e=>setPhoneInput(e.target.value)} placeholder="07XX XXX XXX"/></label>{error&&<p className="form-error">{error}</p>}<button className="button dark full" disabled={busy} onClick={()=>void pay()}>{busy?"Sending payment request...":`Pay KSh ${transaction.fee_amount}`}</button></>}{state==="waiting"&&<div className="payment-wait"><div className="payment-icon">⌁</div><h3>Check your phone</h3><p>Approve the M-Pesa prompt. We are checking the payment automatically.</p><div className="spinner"/></div>}{state==="recovery"&&<><p className="muted">We couldn't confirm the payment automatically. If you completed it, enter the M-Pesa transaction code from your message.</p><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Transaction code"/>{error&&<p className="form-error">{error}</p>}<button className="button dark full" disabled={busy} onClick={()=>void verify()}>{busy?"Verifying...":"Verify payment"}</button></>}{state==="failed"&&<><div className="error-box"><strong>Payment not completed</strong><p>{error}</p></div><button className="button dark full" onClick={()=>{setState("form");setError("")}}>Try again</button></>}{state==="success"&&<div className="success-box"><strong>Contact unlocked</strong><p>You can now contact the other party.</p><button className="button dark" onClick={onClose}>Done</button></div>}</Modal>;
}
