import { useState } from "react";
import type { FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Page } from "@/components/Layout";
import { FormField, Modal } from "@/components/Common";
import { useAuth } from "@/context/AuthContext";
import { deleteMe, updateMe } from "@/services/apiServices";

export function Account(){const{user,refreshUser,logout}=useAuth();const nav=useNavigate();const[phone,setPhone]=useState(user?.phone||"");const[name,setName]=useState(user?.name||"");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");const[deleteOpen,setDeleteOpen]=useState(false);async function save(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");try{await updateMe({name:name.trim()||undefined,phone:phone.trim()||undefined});await refreshUser();setMsg("Profile updated.")}catch(e){setMsg(e instanceof Error?e.message:"Could not update profile.")}finally{setBusy(false)}}async function remove(){setBusy(true);setMsg("");try{await deleteMe();logout();nav("/register",{replace:true})}catch(e){setMsg(e instanceof Error?e.message:"We couldn't delete your account. Please try again.");setBusy(false)}}return <Page title="Account" eyebrow="YOUR ACCOUNT"><div className="account-grid"><form className="form-card" onSubmit={save}><div className="account-avatar">{(user?.email?.[0]||"U").toUpperCase()}</div><h2>Profile</h2><p className="muted">Your account is authenticated with email and password.</p><FormField label="Email"><input value={user?.email||""} disabled/></FormField><FormField label="Name" hint="Optional"><input value={name} onChange={e=>setName(e.target.value)}/></FormField><FormField label="Phone" hint="Optional. Useful for marketplace contact and payments."><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="07XX XXX XXX"/></FormField>{msg&&<p className={msg==="Profile updated."?"success-text":"form-error"}>{msg}</p>}<button className="button dark full" disabled={busy}>{busy?"Saving...":"Save profile"}</button></form><div className="danger-card"><h2>Account deletion</h2><p>Deleting your account permanently removes your account and associated application data. This action cannot be undone.</p><button className="button danger" onClick={()=>setDeleteOpen(true)}>Delete my account</button><p className="muted small-text">Need help instead? <Link to="/home">Contact support from Home.</Link></p></div></div>{deleteOpen&&<Modal title="Delete account" onClose={()=>setDeleteOpen(false)}><p>This will permanently delete your account and associated data. Continue only if you are sure.</p>{msg&&<p className="form-error">{msg}</p>}<div className="form-actions"><button className="button ghost" onClick={()=>setDeleteOpen(false)}>Cancel</button><button className="button danger" disabled={busy} onClick={()=>void remove()}>{busy?"Deleting...":"Delete account"}</button></div></Modal>}</Page>}
