import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { Page } from "@/components/Layout";
import { Badge, Empty, FormField, Loading, Modal, ErrorState } from "@/components/Common";
import { approveDraft, getDraftThread, getDrafts, rejectDraft, sendDraft, submitRoad } from "@/services/apiServices";
import type { ConversationThread, Draft } from "@/types";

export function RoadAgent(){const[query,setQuery]=useState("");const[file,setFile]=useState<File|null>(null);const[result,setResult]=useState<{answer:string;document:string;method:string;cost:number}|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function run(e:FormEvent){e.preventDefault();if(!query.trim())return;setBusy(true);setError("");try{setResult(await submitRoad(query.trim(),file||undefined))}catch(e){setError(e instanceof Error?e.message:"Agent failed. Please try again.")}finally{setBusy(false)}}return <Page title="Road Agent" eyebrow="AI ASSISTANT"><div className="agent-layout"><div className="agent-intro"><Badge tone="success">Available</Badge><h2>Road design assistance</h2><p>Ask the Road Agent questions and receive road-related assistance. You can also attach a document for temporary, query-scoped analysis.</p></div><form className="form-card" onSubmit={run}><FormField label="Your question"><textarea rows={8} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask anything about your road design task..."/></FormField><FormField label="Attach a document" hint="Optional. The file is uploaded for processing with this query."><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<small>{file.name}</small>}</FormField>{error&&<p className="form-error">{error}</p>}<button className="button dark full" disabled={busy}>{busy?"Running...":"Run Road Agent"}</button></form>{result&&<div className="result-card"><div className="card-row"><h3>Response</h3><Badge>{result.method}</Badge></div><div className="result-text">{result.answer}</div>{result.document&&<p className="muted">Document: {result.document}</p>}<small>Estimated cost: {result.cost}</small></div>}</div></Page>}

export function WhatsAppAgent(){const[drafts,setDrafts]=useState<Draft[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selected,setSelected]=useState<Draft|null>(null);const[thread,setThread]=useState<ConversationThread|null>(null);const[edited,setEdited]=useState("");async function load(){setLoading(true);try{setDrafts(await getDrafts())}catch(e){setError(e instanceof Error?e.message:"Couldn't load drafts.")}finally{setLoading(false)}}useEffect(()=>{void load()},[]);async function open(d:Draft){setSelected(d);setEdited(d.draft_content);try{setThread(await getDraftThread(d.id))}catch(e){setError(e instanceof Error?e.message:"Couldn't load conversation.")}}async function action(kind:"approve"|"reject"|"send"){if(!selected)return;try{if(kind==="approve")await approveDraft(selected.id,edited);if(kind==="reject")await rejectDraft(selected.id,"Rejected from Campus Hub web app");if(kind==="send")await sendDraft(selected.id);setSelected(null);setThread(null);await load()}catch(e){setError(e instanceof Error?e.message:"Action failed.")}}return <Page title="WhatsApp Assistant" eyebrow="AI ASSISTANT"><div className="agent-intro"><Badge tone="success">Available</Badge><h2>Review replies before they go out</h2><p>Incoming WhatsApp conversations can produce drafts for you to review, edit, approve, reject and send.</p></div>{error&&<div className="error-box"><p>{error}</p></div>}{loading?<Loading label="Loading drafts..."/>:drafts.length===0?<Empty title="No pending drafts" text="New drafts will appear here when the WhatsApp Agent receives a conversation."/>:<div className="draft-grid">{drafts.map(d=><button className="draft-card" key={d.id} onClick={()=>void open(d)}><div className="card-row"><Badge tone="warning">{d.status}</Badge><small>{new Date(d.created_at).toLocaleString("en-KE")}</small></div><h3>{d.customer_name||d.customer_phone||"WhatsApp customer"}</h3><p>{d.draft_content}</p><span>Review draft →</span></button>)}</div>}{selected&&<Modal title={`Draft · ${selected.customer_name||selected.customer_phone||"Customer"}`} onClose={()=>setSelected(null)}><div className="thread">{thread?.messages.map(m=><div key={m.id} className={m.direction==="inbound"?"message inbound":"message outbound"}><span>{m.direction}</span><p>{m.content}</p></div>)}</div><FormField label="Draft reply"><textarea rows={7} value={edited} onChange={e=>setEdited(e.target.value)}/></FormField><div className="form-actions"><button className="button danger" onClick={()=>void action("reject")}>Reject</button><button className="button ghost" onClick={()=>void action("approve")}>Approve</button><button className="button whatsapp" onClick={()=>void action("send")}>Send</button></div></Modal>}</Page>}

export function ComingSoon({title,description}:{title:string;description:string}){return <Page title={title} eyebrow="AI ASSISTANT"><div className="coming-soon"><Badge>Coming soon</Badge><h2>{description}</h2><p>This service is already part of the Campus Hub roadmap and will become available from this workspace when it is ready.</p><Link className="button dark" to="/home">Back to services</Link></div></Page>}
