import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Page } from "@/components/Layout";
import { Feedback } from "@/components/Feedback";
import { Modal, Badge } from "@/components/Common";
import { getBilling, createDonation } from "@/services/apiServices";
import { useAuth } from "@/context/AuthContext";
import type { BillingInfo } from "@/types";

const services=[
  {id:"market",title:"KU Marketplace",desc:"Buy, sell, and find services within the campus community.",icon:"🛍",to:"/marketplace",available:true},
  {id:"whatsapp",title:"WhatsApp Assistant",desc:"Draft replies to customer messages before you send them.",icon:"◉",to:"/agents/whatsapp",available:true},
  {id:"road",title:"Road Design Assistant",desc:"AI assistance for Kenyan road design and engineering workflows.",icon:"⌁",to:"/agents/road",available:true},
  {id:"podcast",title:"Podcast Assistant",desc:"AI tools for planning, producing, and managing podcasts.",icon:"◌",to:"/agents/podcast",available:false},
  {id:"email",title:"Email Assistant",desc:"Draft thoughtful email replies for you to review and send.",icon:"✉",to:"/agents/email",available:false},
];
export function Home(){const{user}=useAuth();const[billing,setBilling]=useState<BillingInfo|null>(null);const[donate,setDonate]=useState(false);useEffect(()=>{getBilling().then(setBilling).catch(()=>undefined)},[]);return <Page title="Get things done." eyebrow="YOUR WORKSPACE"><div className="home-intro"><p>AI-powered campus services, all in one place.</p><div className="home-actions"><Link className="button dark" to="/marketplace">Open marketplace</Link><Link className="button ghost" to="/account">Manage account</Link></div></div>{billing&&<div className="notice"><div><Badge tone="warning">Marketplace</Badge><h3>{billing.notice_title}</h3><p>{billing.notice_message}</p></div></div>}<div className="section-head"><h2>Services</h2><span>{services.filter(s=>s.available).length} available</span></div><div className="service-grid">{services.map(s=><Link key={s.id} to={s.available?s.to:"#"} onClick={e=>{if(!s.available)e.preventDefault()}} className={`service-card ${s.available?"":"disabled"}`}><div className="service-top"><div className="service-icon">{s.icon}</div><Badge tone={s.available?"success":"neutral"}>{s.available?"Available":"Coming soon"}</Badge></div><div><h3>{s.title}</h3><p>{s.desc}</p></div><span className="service-open">{s.available?"Open →":"Currently unavailable"}</span></Link>)}</div><div className="support-card"><div><span className="support-icon">♥</span><div><h3>Support Campus Hub</h3><p>Help us keep building useful services for the campus community.</p></div></div><button className="button dark" onClick={()=>setDonate(true)}>Support the platform</button></div><div className="bottom-tools"><a href={`https://wa.me/${import.meta.env.VITE_SUPPORT_PHONE||"254769966265"}?text=${encodeURIComponent("Hi, I need support with Campus Hub.")}`} target="_blank" rel="noreferrer" className="button ghost small">WhatsApp Support</a><a href={`tel:${import.meta.env.VITE_SUPPORT_PHONE||"+254769966265"}`} className="button ghost small">Call support</a><Feedback screen="home"/></div>{donate&&<DonationModal onClose={()=>setDonate(false)} defaultPhone={user?.phone||""}/>}</Page>}
function DonationModal({onClose,defaultPhone}:{onClose:()=>void;defaultPhone:string}){const[amount,setAmount]=useState("100");const[phone,setPhone]=useState(defaultPhone);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");async function donate(){const n=Number(amount);if(!n||n<=0){setMessage("Enter a valid amount.");return;}setBusy(true);try{const r=await createDonation(n,phone);setMessage(r.message||"Donation request initiated. Check your phone.");}catch(e){setMessage(e instanceof Error?e.message:"Could not initiate donation.");}finally{setBusy(false);}}return <Modal title="Support Campus Hub" onClose={onClose}><p className="muted">Your support helps us keep building useful campus services.</p><label className="field"><span>Amount (KSh)</span><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="1"/></label><label className="field"><span>M-Pesa phone</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="07XX XXX XXX"/></label>{message&&<div className="success-box"><p>{message}</p></div>}<button className="button dark full" disabled={busy} onClick={()=>void donate()}>{busy?"Starting...":"Donate"}</button></Modal>}
