"""add message_type to whatsapp_messages

Revision ID: 1b6642ed05e0
Revises: f6f220b364e6
Create Date: 2026-08-04 06:32:47.465316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6642ed05e0'
down_revision: Union[str, Sequence[str], None] = 'f6f220b364e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('message_type', sa.Enum('TEXT', 'AUDIO', 'IMAGE', name='messagetype'), nullable=False, server_default='TEXT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'message_type')
    # ### end Alembic commands ###
