"""add podcast rule sets and rules

Revision ID: 26d685cd7d0b
Revises: 1b6642ed05e0
Create Date: 2026-08-14 11:09:11.397485

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '26d685cd7d0b'
down_revision: str | Sequence[str] | None = '1b6642ed05e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
