"""add platform payments

Revision ID: 2de6d5828cf1
Revises: 520bfd097a27
Create Date: 2026-09-01 08:34:06.860846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de6d5828cf1'
down_revision: Union[str, Sequence[str], None] = '520bfd097a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('MPESA', name='payment_provider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESSFUL', 'FAILED', 'CANCELLED', 'EXPIRED', name='payment_status'), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('provider_reference')
    )
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_purpose'), 'payments', ['purpose'], unique=False)
    op.create_index(op.f('ix_payments_reference_id'), 'payments', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reference_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_purpose'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
