"""add draft_replies table

Revision ID: 556416a0405b
Revises: f51d9a492ea2
Create Date: 2026-07-25 08:04:25.415754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '556416a0405b'
down_revision: Union[str, Sequence[str], None] = 'f51d9a492ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_replies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('trigger_message_id', sa.String(), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', 'SENT', name='draftstatus'), nullable=False),
    sa.Column('reviewed_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['whatsapp_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_replies_conversation_id'), 'draft_replies', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_draft_replies_status'), 'draft_replies', ['status'], unique=False)
    op.create_index(op.f('ix_draft_replies_trigger_message_id'), 'draft_replies', ['trigger_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_replies_trigger_message_id'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_status'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_conversation_id'), table_name='draft_replies')
    op.drop_table('draft_replies')
    # ### end Alembic commands ###
