"""add transaction payment fields

Revision ID: 931114d333c2
Revises: a1c7e9d42b11
Create Date: 2026-09-14 07:28:51.516314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931114d333c2'
down_revision: Union[str, Sequence[str], None] = 'a1c7e9d42b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_reference', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['payment_reference'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_transactions_payment_reference",
        'transactions',
        type_='unique'
        )
    op.drop_column('transactions', 'paid_at')
    op.drop_column('transactions', 'payment_reference')
    # ### end Alembic commands ###
