"""change of buyer_id to requester_id in WantedPostResponse

Revision ID: e33c8a025b11
Revises: f94f77cc6517
Create Date: 2026-09-08 04:39:56.458810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33c8a025b11'
down_revision: Union[str, Sequence[str], None] = 'f94f77cc6517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
