"""initial tables

Revision ID: f51d9a492ea2
Revises: 41981df33fa3
Create Date: 2026-07-24 18:44:02.216219

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f51d9a492ea2'
down_revision: str | Sequence[str] | None = '41981df33fa3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
