"""add whatsapp_message_id for webhook idempotency

Revision ID: f6f220b364e6
Revises: ca4c3c882c39
Create Date: 2026-07-28 09:05:34.368914

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6f220b364e6'
down_revision: str | Sequence[str] | None = 'ca4c3c882c39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_messages', sa.Column('whatsapp_message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_whatsapp_messages_whatsapp_message_id'), 'whatsapp_messages', ['whatsapp_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_whatsapp_message_id'), table_name='whatsapp_messages')
    op.drop_column('whatsapp_messages', 'whatsapp_message_id')
    # ### end Alembic commands ###
